version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
   # restart: always
    user: '0:0'
    hostname: 'localgitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localgitlab:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '/path/to/gitlab/config:/etc/gitlab'
      - '/path/to/gitlab/logs:/var/log/gitlab'
      - '/path/to/gitlab/opt/gitlab:/var/opt/gitlab'
    shm_size: '256m'
